
-- Question 1
-- which customers have the highest total sales
SELECT TOP(5) Customer_ID,Customer_Name,SUM(SalesAmount)AS Total_Sales
FROM [Customer  sql Dahel] C
JOIN [Orders  sql Dahel] O
ON Customer_ID = O.CustomerID
GROUP BY Customer_ID,Customer_Name
ORDER BY SUM(SalesAMOUNT) DESC;    

-- Question 2
--Which products are the most popular based on the number of orders
SELECT  P.ProductID,P. ProductName, COUNT(Quantity)AS number_of_orders
FROM [Product2 from dahel] P
JOIN [Orders  sql Dahel] O 
ON P.ProductID = O.ProductID
GROUP BY P.ProductID, ProductName
ORDER BY  COUNT(Quantity) DESC;    

-- Question 3
-- What is the average value of orders placed by each customers
SELECT CustomerID, Customer_Name,AVG(SalesAmount)AS Value_Of_Oder
FROM [Customer  sql Dahel] C
Join [Orders  sql Dahel] O
ON Customer_ID = O.CustomerID
GROUP BY CustomerID, Customer_Name  
ORDER BY AVG(SalesAmount) DESC;   


-- Question 4  
-- How much sales revenue is generated from each product category
SELECT ProductName, Category,SUM(SalesAmount)AS Revenue
FROM [Product2 from dahel] P
JOIN [Orders  sql Dahel] O 
ON P.ProductID = O.ProductID 
GROUP BY ProductName, Category
ORDER BY SUM(SalesAmount);    


-- Question 5
-- How many orders has each customers placed
SELECT CustomerID, Customer_Name, COUNT(OrderID)AS Total_Orders
FROM [Customer  sql Dahel] C
JOIN [Orders  sql Dahel] O
ON Customer_ID = O.CustomerID 
GROUP BY CustomerID, Customer_Name
ORDER BY COUNT(OrderID);


-- Question 6 
-- What is the total revenue generated by each product
SELECT P.ProductID,P. ProductName, SUM(SalesAmount)AS Total_Revenue
FROM [Product2 from dahel] P
JOIN [Orders  sql Dahel] O
ON P.ProductID = O.ProductID 
GROUP BY P.ProductID,P.ProductName
ORDER BY SUM(SalesAmount)DESC;     


-- Question 7  
-- What is the average sale amount per customer 
SELECT Customer_ID,Customer_Name,AVG(SalesAmount)AS Avg_Sales_Amount 
FROM  [Customer  sql Dahel] D
JOIN [Orders  sql Dahel] O 
ON Customer_ID = O.CustomerID 
GROUP BY Customer_ID,Customer_Name 
ORDER BY AVG(SalesAmount);  

-- Question 8 
-- Who are the top spending customers
SELECT TOP(10) Customer_ID,Customer_Name,SUM(SalesAmount)AS Total_Amount_Spent
FROM  [Customer  sql Dahel] D
JOIN [Orders  sql Dahel] O 
ON Customer_ID = O.CustomerID 
GROUP BY Customer_ID,Customer_Name 
ORDER BY SUM(SalesAmount) DESC;   


-- Question 9
-- How do the sales of each product trend over time
SELECT SalesDate,ProductName,SUM(SalesAmount)AS Sales,SUM(Quantity)AS Quantity_Sold
FROM [Product2 from dahel] P 
JOIN [Orders  sql Dahel] O 
ON  P.ProductID = O.ProductID
GROUP BY  SalesDate,ProductName
ORDER BY SalesDate;

 
 -- Question 10 
--How many customer have made multiple purchase? 
SELECT O.CustomerID,COUNT(*) AS multiple_buy_customers
FROM [Customer  sql Dahel] C
JOIN [Orders  sql Dahel] O
ON C. Customer_ID = O.CustomerID
GROUP BY O.CustomerID
HAVING COUNT(O.OrderID) > 1;


 -- Question 11
-- How many units of each product have been ordered?
SELECT P.ProductID,P.ProductName, SUM(Quantity)AS total_units_ordered
FROM [Product2 from dahel] P
JOIN [Orders  sql Dahel] O
ON P.ProductID = O.ProductID
GROUP BY P.ProductID,P.ProductName
ORDER BY total_units_ordered DESC;

-- Question 12
-- How do sale perform in diff store ID?   
SELECT StoreID, SUM(SalesAmount)AS total_sales
FROM [Orders  sql Dahel]
GROUP BY StoreID
ORDER BY total_sales DESC;





